#!/bin/bash

script=$(readlink -f $0)
scriptdir=$(dirname $script)
installdir=$HOME
syncdir=$scriptdir/dotfile.d
files=$(ls -a "$syncdir")
exclude=('\..+\.swp' '\.git')

function usage () {
	echo "dotfile -i (install)"
	echo "dotfile -a DOTFILE-PATH (relative to \$HOME) (add)"
	echo "dotfile -h"
	[[ -n $1 ]] && exit $1
	exit 0
}

dotfiles=($(awk '/^\.[^\.]+.*$/ {print $1}' <<< $files))
for i in ${exclude[@]}; do
	dotfiles=($(awk "BEGIN {RS=\" \"}; /$i/ {next}; {print}"\
	  	<<< ${dotfiles[*]}))
done

function install () {
	for i in ${dotfiles[@]}; do
		[[ -n $i ]] && {
			cp -rT "$syncdir/$i" "$installdir/$i"
		}
	done
	exit
}

function add () {
	parentdir=($(awk '/^[^\/]*$/ {print "0", $0; next} \
		{match($0, /^(.+)\/(.*)$/, arr); print "1", arr[1], arr[2]}' <<< $1))
	bool=${parentdir[0]}
	filea=${parentdir[1]}
	fileb=${parentdir[2]}
	[[ -e "$installdir/$filea" ]] || echo "file doesn't exist" && exit 1
	if [[ $bool == 0 ]]; then
		cp -rT "$installdir/$filea" "$syncdir/$filea"
	else
		mkdir -p "$syncdir/$filea"
		cp -rT "$installdir/$filea/$fileb" "$syncdir/$filea/$fileb"
	fi
	exit
}

while getopts ":isa:" flag; do
	case $flag in
		i)
			install
			;;
		a)
			add $OPTARG
			;;
		h)
			usage
			;;
		*)
			usage 1
			;;
	esac
done

eval "$script -h"
